# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
# Triggers the workflow for every project push
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linter-and-jest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Linter and Jest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn
        
      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

  cypress-run:
    runs-on: ubuntu-16.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
